name: Check Elastic Beanstalk Docker Version

on:

  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:

  check-version:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - name: Run checker
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python check_version.py

      - name: Commit updated version
        if: success()
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          if git diff --quiet; then
            echo "No changes."
            exit 0
          fi

          git add version.txt
          git commit -m "Update tracked Docker AL2023 version"
          git push

      - name: Notify Slack on Failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          curl -X POST \
          -H 'Content-type: application/json' \
          --data "{\"text\":\"❌ *Elastic Beanstalk Docker AL2023 Workflow Failed*\\n\\nWorkflow failed with error. Please check Workflow in GitHub for details.\\n\\n<$GITHUB_RUN_URL|View Failed Workflow Run>\"}" \
          $SLACK_WEBHOOK_URL
